INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (1, 'AF', 'Afghanistan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (2, 'AL', 'Albania');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (3, 'AQ', 'Antarctica');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (4, 'DZ', 'Algeria');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (5, 'AS', 'American Samoa');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (6, 'AD', 'Andorra');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (7, 'AO', 'Angola');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (8, 'AG', 'Antigua and Barbuda');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (9, 'AZ', 'Azerbaijan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (10, 'AR', 'Argentina');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (11, 'AU', 'Australia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (12, 'AT', 'Austria');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (13, 'BS', 'Bahamas');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (14, 'BH', 'Bahrain');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (15, 'BD', 'Bangladesh');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (16, 'AM', 'Armenia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (17, 'BB', 'Barbados');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (18, 'BE', 'Belgium');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (19, 'BM', 'Bermuda');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (20, 'BT', 'Bhutan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (21, 'BO', 'Bolivia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (22, 'BA', 'Bosnia and Herzegovina');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (23, 'BW', 'Botswana');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (24, 'BV', 'Bouvet Island');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (25, 'BR', 'Brazil');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (26, 'BZ', 'Belize');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (27, 'IO', 'British Indian Ocean Territory');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (28, 'SB', 'Solomon Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (29, 'VG', 'British Virgin Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (30, 'BN', 'Brunei Darussalam');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (31, 'BG', 'Bulgaria');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (32, 'MM', 'Myanmar');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (33, 'BI', 'Burundi');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (34, 'BY', 'Belarus');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (35, 'KH', 'Cambodia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (36, 'CM', 'Cameroon');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (37, 'CA', 'Canada');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (38, 'CV', 'Cape Verde');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (39, 'KY', 'Cayman Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (40, 'CF', 'Central African');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (41, 'LK', 'Sri Lanka');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (42, 'TD', 'Chad');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (43, 'CL', 'Chile');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (44, 'CN', 'China');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (45, 'TW', 'Taiwan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (46, 'CX', 'Christmas Island');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (47, 'CC', 'Cocos (Keeling) Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (48, 'CO', 'Colombia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (49, 'KM', 'Comoros');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (50, 'YT', 'Mayotte');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (51, 'CG', 'Republic of the Congo');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (52, 'CD', 'The Democratic Republic Of The Congo');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (53, 'CK', 'Cook Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (54, 'CR', 'Costa Rica');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (55, 'HR', 'Croatia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (56, 'CU', 'Cuba');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (57, 'CY', 'Cyprus');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (58, 'CZ', 'Czech Republic');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (59, 'BJ', 'Benin');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (60, 'DK', 'Denmark');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (61, 'DM', 'Dominica');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (62, 'DO', 'Dominican Republic');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (63, 'EC', 'Ecuador');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (64, 'SV', 'El Salvador');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (65, 'GQ', 'Equatorial Guinea');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (66, 'ET', 'Ethiopia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (67, 'ER', 'Eritrea');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (68, 'EE', 'Estonia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (69, 'FO', 'Faroe Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (70, 'FK', 'Falkland Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (71, 'GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (72, 'FJ', 'Fiji');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (73, 'FI', 'Finland');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (74, 'AX', 'Ç?land Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (75, 'FR', 'France');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (76, 'GF', 'French Guiana');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (77, 'PF', 'French Polynesia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (78, 'TF', 'French Southern Territories');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (79, 'DJ', 'Djibouti');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (80, 'GA', 'Gabon');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (81, 'GE', 'Georgia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (82, 'GM', 'Gambia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (83, 'PS', 'Occupied Palestinian Territory');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (84, 'DE', 'Germany');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (85, 'GH', 'Ghana');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (86, 'GI', 'Gibraltar');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (87, 'KI', 'Kiribati');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (88, 'GR', 'Greece');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (89, 'GL', 'Greenland');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (90, 'GD', 'Grenada');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (91, 'GP', 'Guadeloupe');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (92, 'GU', 'Guam');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (93, 'GT', 'Guatemala');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (94, 'GN', 'Guinea');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (95, 'GY', 'Guyana');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (96, 'HT', 'Haiti');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (97, 'HM', 'Heard Island and McDonald Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (98, 'VA', 'Vatican City State');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (99, 'HN', 'Honduras');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (100, 'HK', 'Hong Kong');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (101, 'HU', 'Hungary');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (102, 'IS', 'Iceland');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (103, 'IN', 'India');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (104, 'ID', 'Indonesia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (105, 'IR', 'Islamic Republic of Iran');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (106, 'IQ', 'Iraq');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (107, 'IE', 'Ireland');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (108, 'IL', 'Israel');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (109, 'IT', 'Italy');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (110, 'CI', 'CÇïte dIvoire');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (111, 'JM', 'Jamaica');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (112, 'JP', 'Japan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (113, 'KZ', 'Kazakhstan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (114, 'JO', 'Jordan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (115, 'KE', 'Kenya');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (116, 'KP', 'Democratic Peoples Republic of Korea');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (117, 'KR', 'Republic of Korea');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (118, 'KW', 'Kuwait');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (119, 'KG', 'Kyrgyzstan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (120, 'LA', 'Lao Peoples Democratic Republic');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (121, 'LB', 'Lebanon');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (122, 'LS', 'Lesotho');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (123, 'LV', 'Latvia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (124, 'LR', 'Liberia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (125, 'LY', 'Libyan Arab Jamahiriya');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (126, 'LI', 'Liechtenstein');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (127, 'LT', 'Lithuania');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (128, 'LU', 'Luxembourg');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (129, 'MO', 'Macao');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (130, 'MG', 'Madagascar');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (131, 'MW', 'Malawi');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (132, 'MY', 'Malaysia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (133, 'MV', 'Maldives');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (134, 'ML', 'Mali');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (135, 'MT', 'Malta');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (136, 'MQ', 'Martinique');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (137, 'MR', 'Mauritania');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (138, 'MU', 'Mauritius');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (139, 'MX', 'Mexico');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (140, 'MC', 'Monaco');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (141, 'MN', 'Mongolia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (142, 'MD', 'Republic of Moldova');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (143, 'MS', 'Montserrat');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (144, 'MA', 'Morocco');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (145, 'MZ', 'Mozambique');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (146, 'OM', 'Oman');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (147, 'NA', 'Namibia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (148, 'NR', 'Nauru');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (149, 'NP', 'Nepal');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (150, 'NL', 'Netherlands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (151, 'AN', 'Netherlands Antilles');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (152, 'AW', 'Aruba');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (153, 'NC', 'New Caledonia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (154, 'VU', 'Vanuatu');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (155, 'NZ', 'New Zealand');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (156, 'NI', 'Nicaragua');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (157, 'NE', 'Niger');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (158, 'NG', 'Nigeria');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (159, 'NU', 'Niue');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (160, 'NF', 'Norfolk Island');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (161, 'NO', 'Norway');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (162, 'MP', 'Northern Mariana Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (163, 'UM', 'United States Minor Outlying Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (164, 'FM', 'Federated States of Micronesia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (165, 'MH', 'Marshall Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (166, 'PW', 'Palau');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (167, 'PK', 'Pakistan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (168, 'PA', 'Panama');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (169, 'PG', 'Papua New Guinea');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (170, 'PY', 'Paraguay');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (171, 'PE', 'Peru');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (172, 'PH', 'Philippines');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (173, 'PN', 'Pitcairn');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (174, 'PL', 'Poland');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (175, 'PT', 'Portugal');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (176, 'GW', 'Guinea-Bissau');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (177, 'TL', 'Timor-Leste');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (178, 'PR', 'Puerto Rico');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (179, 'QA', 'Qatar');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (180, 'RE', 'RÇ¸union');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (181, 'RO', 'Romania');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (182, 'RU', 'Russian Federation');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (183, 'RW', 'Rwanda');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (184, 'SH', 'Saint Helena');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (185, 'KN', 'Saint Kitts and Nevis');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (186, 'AI', 'Anguilla');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (187, 'LC', 'Saint Lucia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (188, 'PM', 'Saint-Pierre and Miquelon');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (189, 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (190, 'SM', 'San Marino');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (191, 'ST', 'Sao Tome and Principe');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (192, 'SA', 'Saudi Arabia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (193, 'SN', 'Senegal');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (194, 'SC', 'Seychelles');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (195, 'SL', 'Sierra Leone');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (196, 'SG', 'Singapore');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (197, 'SK', 'Slovakia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (198, 'VN', 'Vietnam');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (199, 'SI', 'Slovenia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (200, 'SO', 'Somalia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (201, 'ZA', 'South Africa');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (202, 'ZW', 'Zimbabwe');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (203, 'ES', 'Spain');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (204, 'EH', 'Western Sahara');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (205, 'SD', 'Sudan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (206, 'SR', 'Suriname');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (207, 'SJ', 'Svalbard and Jan Mayen');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (208, 'SZ', 'Swaziland');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (209, 'SE', 'Sweden');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (210, 'CH', 'Switzerland');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (211, 'SY', 'Syrian Arab Republic');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (212, 'TJ', 'Tajikistan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (213, 'TH', 'Thailand');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (214, 'TG', 'Togo');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (215, 'TK', 'Tokelau');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (216, 'TO', 'Tonga');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (217, 'TT', 'Trinidad and Tobago');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (218, 'AE', 'United Arab Emirates');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (219, 'TN', 'Tunisia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (220, 'TR', 'Turkey');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (221, 'TM', 'Turkmenistan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (222, 'TC', 'Turks and Caicos Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (223, 'TV', 'Tuvalu');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (224, 'UG', 'Uganda');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (225, 'UA', 'Ukraine');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (226, 'MK', 'The Former Yugoslav Republic of Macedonia');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (227, 'EG', 'Egypt');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (228, 'GB', 'United Kingdom');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (229, 'IM', 'Isle of Man');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (230, 'TZ', 'United Republic Of Tanzania');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (231, 'US', 'United States');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (232, 'VI', 'U.S. Virgin Islands');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (233, 'BF', 'Burkina Faso');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (234, 'UY', 'Uruguay');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (235, 'UZ', 'Uzbekistan');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (236, 'VE', 'Venezuela');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (237, 'WF', 'Wallis and Futuna');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (238, 'WS', 'Samoa');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (239, 'YE', 'Yemen');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (240, 'CS', 'Serbia and Montenegro');
INSERT INTO universityx.country (idcountry, codeiso2, label) VALUES (241, 'ZM', 'Zambia');